# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProxyMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProxyMsg.proto',
  package='proxy.msg',
  syntax='proto2',
  serialized_pb=_b('\n\x0eProxyMsg.proto\x12\tproxy.msg\"}\n\x08ProxyMsg\x12\x14\n\x0cplace_holder\x18\x01 \x01(\x0c\x12\x11\n\tcheck_sum\x18\x02 \x01(\r\x12\x0b\n\x03\x63md\x18\x03 \x01(\r\x12\x0e\n\x06subcmd\x18\x04 \x01(\r\x12\x0b\n\x03seq\x18\x05 \x01(\r\x12\x0c\n\x04\x62ody\x18\x06 \x01(\x0c\x12\x10\n\x08\x65rr_code\x18\x07 \x02(\r\"b\n\x0fProxyConnectReq\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"!\n\x0fProxyConnectRsp\x12\x0e\n\x06result\x18\x01 \x02(\r*\x19\n\x07\x42IG_CMD\x12\x0e\n\tServerCmd\x10\x80\n*\'\n\x07SUB_CMD\x12\r\n\tSubCmd0x1\x10\x01\x12\r\n\tSubCmd0x2\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_BIG_CMD = _descriptor.EnumDescriptor(
  name='BIG_CMD',
  full_name='proxy.msg.BIG_CMD',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ServerCmd', index=0, number=1280,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=291,
  serialized_end=316,
)
_sym_db.RegisterEnumDescriptor(_BIG_CMD)

BIG_CMD = enum_type_wrapper.EnumTypeWrapper(_BIG_CMD)
_SUB_CMD = _descriptor.EnumDescriptor(
  name='SUB_CMD',
  full_name='proxy.msg.SUB_CMD',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SubCmd0x1', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SubCmd0x2', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=318,
  serialized_end=357,
)
_sym_db.RegisterEnumDescriptor(_SUB_CMD)

SUB_CMD = enum_type_wrapper.EnumTypeWrapper(_SUB_CMD)
ServerCmd = 1280
SubCmd0x1 = 1
SubCmd0x2 = 2



_PROXYMSG = _descriptor.Descriptor(
  name='ProxyMsg',
  full_name='proxy.msg.ProxyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='place_holder', full_name='proxy.msg.ProxyMsg.place_holder', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='check_sum', full_name='proxy.msg.ProxyMsg.check_sum', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='proxy.msg.ProxyMsg.cmd', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subcmd', full_name='proxy.msg.ProxyMsg.subcmd', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='proxy.msg.ProxyMsg.seq', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='proxy.msg.ProxyMsg.body', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='proxy.msg.ProxyMsg.err_code', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=154,
)


_PROXYCONNECTREQ = _descriptor.Descriptor(
  name='ProxyConnectReq',
  full_name='proxy.msg.ProxyConnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proxy.msg.ProxyConnectReq.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='proxy.msg.ProxyConnectReq.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='proxy.msg.ProxyConnectReq.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='proxy.msg.ProxyConnectReq.username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='proxy.msg.ProxyConnectReq.password', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=254,
)


_PROXYCONNECTRSP = _descriptor.Descriptor(
  name='ProxyConnectRsp',
  full_name='proxy.msg.ProxyConnectRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='proxy.msg.ProxyConnectRsp.result', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=289,
)

DESCRIPTOR.message_types_by_name['ProxyMsg'] = _PROXYMSG
DESCRIPTOR.message_types_by_name['ProxyConnectReq'] = _PROXYCONNECTREQ
DESCRIPTOR.message_types_by_name['ProxyConnectRsp'] = _PROXYCONNECTRSP
DESCRIPTOR.enum_types_by_name['BIG_CMD'] = _BIG_CMD
DESCRIPTOR.enum_types_by_name['SUB_CMD'] = _SUB_CMD

ProxyMsg = _reflection.GeneratedProtocolMessageType('ProxyMsg', (_message.Message,), dict(
  DESCRIPTOR = _PROXYMSG,
  __module__ = 'ProxyMsg_pb2'
  # @@protoc_insertion_point(class_scope:proxy.msg.ProxyMsg)
  ))
_sym_db.RegisterMessage(ProxyMsg)

ProxyConnectReq = _reflection.GeneratedProtocolMessageType('ProxyConnectReq', (_message.Message,), dict(
  DESCRIPTOR = _PROXYCONNECTREQ,
  __module__ = 'ProxyMsg_pb2'
  # @@protoc_insertion_point(class_scope:proxy.msg.ProxyConnectReq)
  ))
_sym_db.RegisterMessage(ProxyConnectReq)

ProxyConnectRsp = _reflection.GeneratedProtocolMessageType('ProxyConnectRsp', (_message.Message,), dict(
  DESCRIPTOR = _PROXYCONNECTRSP,
  __module__ = 'ProxyMsg_pb2'
  # @@protoc_insertion_point(class_scope:proxy.msg.ProxyConnectRsp)
  ))
_sym_db.RegisterMessage(ProxyConnectRsp)


# @@protoc_insertion_point(module_scope)
